apiVersion: kubedgeoperators.kubedge.cloud/v1alpha1
kind: MMESim
metadata:
  name: kubedge-mmesim-cluster
spec:
  targetState: deployed
  source:
    type: local
    location: /opt/kubedge-operators/mmesim-templates/classic.yaml
  fsbs:
    replicas: 1
    selector:
      matchLabels:
        app: fsb
    template:
      metadata:
        labels:
          app: fsb
      spec:
        containers:
        - name: main
          image: hack4easy/mmesim-fsb:v0.2.24
          imagePullPolicy: IfNotPresent
          command: ["/mmesim-fsb"]
          ports:
            - containerPort: 8082
  gpbs:
    replicas: 1
    selector:
      matchLabels:
        app: gpb
    template:
      metadata:
        labels:
          app: gpb
      spec:
        containers:
        - name: main
          image: hack4easy/mmesim-gpb:v0.2.24
          imagePullPolicy: IfNotPresent
          command: ["/mmesim-gpb"]
          ports:
            - containerPort: 8083
  lcs:
    replicas: 1
    selector:
      matchLabels:
        app: lc
    template:
      metadata:
        labels:
          app: lc
      spec:
        containers:
        - name: main
          image: hack4easy/mmesim-lc:v0.2.24
          imagePullPolicy: IfNotPresent
          command: ["/mmesim-lc"]
          ports:
            - containerPort: 8084
  ncbs:
    replicas: 1
    selector:
      matchLabels:
        app: ncb
    template:
      metadata:
        labels:
          app: ncb
      spec:
        containers:
        - name: main
          image: hack4easy/mmesim-ncb:v0.2.24
          imagePullPolicy: IfNotPresent
          command: ["/mmesim-ncb"]
          ports:
            - containerPort: 8085
